clc;
close all;
gaussian=im2double(imread('gaussian.png'));
subplot(221);
imshow(gaussian);
title('高斯噪声图片');
salt=im2double(imread('salt&pepper.png'));
subplot(222);
imshow(salt);
title('椒盐噪声图片');
%几何均值滤波
h=fspecial('average',3);%创建一个均值(5*5)
fdata=1./(imfilter(1./gaussian,h));%前面是图片，后面是模板
subplot(223);
imshow(fdata);
imwrite(fdata,'gaussian-harm-average.png');
title('高斯噪声图片-谐波均值滤波');
h=fspecial('average',3);%创建一个均值(5*5)
fdata=1./(imfilter(1./(salt),h));%前面是图片，后面是模板
subplot(224);
imshow(fdata);
imwrite(fdata,'salt&pepper-harm-average.png');
title('椒盐噪声图片-谐波均值滤波');