clc;
close all;
salt=im2double(imread('salt&pepper.png'));
[M,N]=size(salt);
k=ones(M,N);
subplot(221);
imshow(salt);
title('椒盐噪声图片');
salt=im2double(imread('salt&pepper.png'));
subplot(222);
imshow(salt);
title('椒盐噪声图片');
%逆谐波均值滤波
h=fspecial('average',3);%创建一个均值
fdata1=imfilter(salt.^3,h);%前面是图片，后面是模板
fdata2=imfilter(salt.^2,h);
fdata=fdata1./fdata2;
subplot(223);
imshow(fdata);
imwrite(fdata,'salt-antiharm-average-Q=2.png');
title('椒盐噪声图片-逆谐波均值滤波-Q=2');
h=fspecial('average',3);%创建一个均值(5*5)
fdata1=imfilter(salt.^-1,h);%前面是图片，后面是模板
fdata2=imfilter(salt.^-2,h);
fdata=fdata1./fdata2;
subplot(224);
imshow(fdata);
imwrite(fdata,'salt-antiharm-average-Q=-2.png');
title('椒盐噪声图片-谐波均值滤波-Q=-2');